export enum NotificationTypeEnum {
  POST_LIKE = 'POST_LIKE',
  POST_COMMENT = 'POST_COMMENT',
  ORDER_RECEIVED = 'ORDER_RECEIVED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  WEDDING = 'wedding',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  DEFAULT = 'DEFAULT',

}






